gen_z_phrases = [
    ('boujee af', 1),
    ('on fleek', 1),
    ('goals', 1),
    ('on point', 1),
    ('fire', 1),
    ('yasss', 1),
    ('lit fam', 1),
    ('bae', 1),
    ('slay', 1),
    ('queen', 1),
    ('king', 1),
    ('go hard', 1),
    ('boss', 1),
    ('badass', 1),
    ('epic', 1),
    ('legendary', 1),
    ('fierce', 1),
    ('dope', 1),
    ('sick', 1),
    ("crushin' it", 1),
    ('stunner', 1),
    ('power move', 1),
    ('jaw-dropping', 1),
    ('mind-blowing', 1),
    ('out of this world', 1),
    ('smooth operator', 1),
    ('game-changer', 1),
    ('genius', 1),
    ('prodigy', 1),
    ('phenomenal', 1),
    ('majestic', 1),
    ('divine', 1),
    ('goddess', 1),
    ('godlike', 1),
    ('trendsetter', 1),
    ('innovator', 1),
    ('disruptor', 1),
    ('influencer', 1),
    ('pioneer', 1),
    ('trailblazer', 1),
    ('frontrunner', 1),
    ('visionary', 1),
    ('icon', 1),
    ('superstar', 1),
    ('guru', 1),
    ('maestro', 1),
    ('expert', 1),
    ('ace', 1),
    ('champion', 1),
    ('winner', 1),
    ('trash af', 0),
    ('wack af', 0),
    ('dead af', 0),
    ('lame', 0),
    ('boring', 0),
    ('weak', 0),
    ('lousy', 0),
    ('useless', 0),
    ('inferior', 0),
    ('disappointing', 0),
    ('lacking', 0),
    ('mediocre', 0),
    ('subpar', 0),
    ('second-rate', 0),
    ('unsatisfactory', 0),
    ]

table = "| Number | Phrase | Sentiment\n"
table += "| --- | --- | ---\n"
for i, (phrase, sentiment) in enumerate(gen_z_phrases):
    table += f"| {i+1}. | {phrase} | {'Positive' if sentiment == 1 else 'Negative'}\n"

with open("result.txt", "w") as f:
    f.write(table)
